import { Video } from '../models/types';

const GTV = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample';
const FLUTTER = 'https://flutter.github.io/assets-for-api-docs/assets/videos';

function gtv(file: string, image: string) {
  return {
    videoUrl: `${GTV}/${file}`,
    thumbnailUrl: `${GTV}/images/${image}`,
    fallbackVideoUrl: `${FLUTTER}/bee.mp4`,
  };
}

export const seededVideos: Video[] = [
  {
    id: 'video_001',
    title: 'Why Do Stars Shine?',
    description: 'Discover why stars shine in the night sky, in a calm science story for curious kids.',
    ...gtv('ForBiggerJoyrides.mp4', 'ForBiggerJoyrides.jpg'),
    category: 'science',
    language: 'en',
    minAge: 6,
    maxAge: 12,
    durationSeconds: 15,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Learning',
    tags: ['science', 'space', 'stars'],
  },
  {
    id: 'video_002',
    title: 'Meet the African Elephant',
    description: 'Walk with a gentle giant and learn how elephants live, eat, and care for their families.',
    ...gtv('ElephantsDream.mp4', 'ElephantsDream.jpg'),
    category: 'animals',
    language: 'en',
    minAge: 3,
    maxAge: 12,
    durationSeconds: 653,
    orientation: 'horizontal',
    isShort: false,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Nature',
    tags: ['animals', 'africa', 'elephant'],
  },
  {
    id: 'video_003',
    title: 'Draw a Lion With Me',
    description: 'Follow simple shapes and turn them into a friendly lion you can color later.',
    ...gtv('ForBiggerFun.mp4', 'ForBiggerFun.jpg'),
    category: 'drawing',
    language: 'en',
    minAge: 5,
    maxAge: 10,
    durationSeconds: 60,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Studio',
    tags: ['drawing', 'lion', 'art'],
  },
  {
    id: 'video_004',
    title: 'Counting From 1 to 20',
    description: 'Count along with cheerful numbers, pauses, and plenty of chances to join in.',
    videoUrl: `${FLUTTER}/bee.mp4`,
    thumbnailUrl: `${GTV}/images/BigBuckBunny.jpg`,
    fallbackVideoUrl: `${FLUTTER}/butterfly.mp4`,
    category: 'education',
    language: 'en',
    minAge: 3,
    maxAge: 8,
    durationSeconds: 16,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Learning',
    tags: ['counting', 'math', 'numbers'],
  },
  {
    id: 'video_005',
    title: 'The Clever Hare — Ethiopian Story',
    description: 'A beloved Ethiopian folktale about a small hare who uses kindness and wit.',
    ...gtv('Sintel.mp4', 'Sintel.jpg'),
    category: 'stories',
    language: 'am',
    minAge: 5,
    maxAge: 12,
    durationSeconds: 888,
    orientation: 'horizontal',
    isShort: false,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Stories',
    tags: ['ethiopia', 'folktale', 'hare'],
  },
  {
    id: 'video_006',
    title: 'How Rainbows Are Made',
    description: 'Sunlight, raindrops, and a little science turn into a rainbow you can understand.',
    ...gtv('ForBiggerEscapes.mp4', 'ForBiggerEscapes.jpg'),
    category: 'science',
    language: 'en',
    minAge: 6,
    maxAge: 10,
    durationSeconds: 15,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Learning',
    tags: ['science', 'weather', 'rainbow'],
  },
  {
    id: 'video_007',
    title: 'Learn 5 English Animal Names',
    description: 'Hear, say, and remember five friendly animal names in English.',
    videoUrl: `${FLUTTER}/butterfly.mp4`,
    thumbnailUrl: `${GTV}/images/ElephantsDream.jpg`,
    fallbackVideoUrl: `${FLUTTER}/bee.mp4`,
    category: 'language',
    language: 'en',
    minAge: 3,
    maxAge: 8,
    durationSeconds: 10,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Languages',
    tags: ['english', 'animals', 'words'],
  },
  {
    id: 'video_008',
    title: 'Easy Paper Airplane',
    description: 'Fold along, pause, and fly a simple paper airplane that really glides.',
    ...gtv('ForBiggerBlazes.mp4', 'ForBiggerBlazes.jpg'),
    category: 'drawing',
    language: 'en',
    minAge: 6,
    maxAge: 12,
    durationSeconds: 15,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Studio',
    tags: ['craft', 'airplane', 'making'],
  },
  {
    id: 'video_009',
    title: 'How Volcanoes Work',
    description: 'See how magma, pressure, and rock create volcanoes — without the scary bits.',
    ...gtv('ForBiggerMeltdowns.mp4', 'ForBiggerMeltdowns.jpg'),
    category: 'science',
    language: 'en',
    minAge: 7,
    maxAge: 12,
    durationSeconds: 15,
    orientation: 'vertical',
    isShort: true,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Learning',
    tags: ['volcano', 'earth', 'science'],
  },
  {
    id: 'video_010',
    title: 'Bedtime Story: The Little Moon',
    description: 'A quiet story about a little moon who learns to share her light.',
    ...gtv('BigBuckBunny.mp4', 'BigBuckBunny.jpg'),
    category: 'stories',
    language: 'en',
    minAge: 3,
    maxAge: 8,
    durationSeconds: 596,
    orientation: 'horizontal',
    isShort: false,
    isEducational: true,
    isReligious: false,
    creator: 'KIDO Stories',
    tags: ['bedtime', 'moon', 'calm'],
  },
];
